slack:
  bot_token: SLACK_BOT_TOKEN
  app_token: SLACK_APP_TOKEN
  product_internal_channel:
    am: SLACK_INTERNAL_CHANNEL
    ccd: SLACK_INTERNAL_CHANNEL_CCD
    cui: SLACK_INTERNAL_CHANNEL
    em: SLACK_INTERNAL_CHANNEL
    xui: SLACK_INTERNAL_CHANNEL_XUI
    fees-pay: SLACK_INTERNAL_CHANNEL_FP
    hmc: SLACK_INTERNAL_CHANNEL_HMC
    idam: SLACK_INTERNAL_CHANNEL
    lau: SLACK_INTERNAL_CHANNEL
    pcq: SLACK_INTERNAL_CHANNEL
    rd: SLACK_INTERNAL_CHANNEL_RD
    tm: SLACK_INTERNAL_CHANNEL
  product_support_channel:
    am: SLACK_SUPPORT_CHANNEL_AM
    ccd: SLACK_SUPPORT_CHANNEL_CCD
    cui: SLACK_SUPPORT_CHANNEL_CUI
    em: SLACK_SUPPORT_CHANNEL_EM
    xui: SLACK_SUPPORT_CHANNEL_XUI
    fees-pay: SLACK_SUPPORT_CHANNEL_FP
    hmc: SLACK_SUPPORT_CHANNEL_HMC
    idam: SLACK_SUPPORT_CHANNEL_IDAM
    lau: SLACK_SUPPORT_CHANNEL_LAU
    pcq: SLACK_SUPPORT_CHANNEL_PCQ
    rd: SLACK_SUPPORT_CHANNEL_RD
    tm: SLACK_SUPPORT_CHANNEL_TM

app_insights:
  instrumentation_key: APP_INSIGHTS_INSTRUMENTATION_KEY
